// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2jZ4gzMNq7yxIeIp9g0-v0lbgyeUXTRI',
    appId: '1:820359726048:web:1b04868244c8a7636ae185',
    messagingSenderId: '820359726048',
    projectId: 'hostelfix-5eb4d',
    authDomain: 'hostelfix-5eb4d.firebaseapp.com',
    storageBucket: 'hostelfix-5eb4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19JtT3GGsNScoiaVgcebWjvsSCaGUTRw',
    appId: '1:820359726048:android:96fc11a4c758e8286ae185',
    messagingSenderId: '820359726048',
    projectId: 'hostelfix-5eb4d',
    storageBucket: 'hostelfix-5eb4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXpL97yerdtheke1DKHNdfxHQcyDvqTVQ',
    appId: '1:820359726048:ios:761329fdbc21965e6ae185',
    messagingSenderId: '820359726048',
    projectId: 'hostelfix-5eb4d',
    storageBucket: 'hostelfix-5eb4d.firebasestorage.app',
    iosBundleId: 'com.example.hostelFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXpL97yerdtheke1DKHNdfxHQcyDvqTVQ',
    appId: '1:820359726048:ios:761329fdbc21965e6ae185',
    messagingSenderId: '820359726048',
    projectId: 'hostelfix-5eb4d',
    storageBucket: 'hostelfix-5eb4d.firebasestorage.app',
    iosBundleId: 'com.example.hostelFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2jZ4gzMNq7yxIeIp9g0-v0lbgyeUXTRI',
    appId: '1:820359726048:web:5577380a576d5c946ae185',
    messagingSenderId: '820359726048',
    projectId: 'hostelfix-5eb4d',
    authDomain: 'hostelfix-5eb4d.firebaseapp.com',
    storageBucket: 'hostelfix-5eb4d.firebasestorage.app',
  );
}
